-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.empleado
(
    id serial,
    nombre character varying(50) NOT NULL,
    apellido character varying(50),
    telefono character varying(15) NOT NULL,
    email character varying(70) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.vehiculo
(
    id serial,
    tipo character varying(20) NOT NULL,
    matricula character varying(15),
    modelo character varying(20) NOT NULL,
    fabricante character varying(20) NOT NULL,
    fecha_ad date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.prestamo
(
    id serial,
    id_empleado integer NOT NULL,
    id_vehiculo integer NOT NULL,
    fecha_ini date NOT NULL,
    fecha_dev date,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.prestamo
    ADD CONSTRAINT fk_empleado FOREIGN KEY (id_empleado)
    REFERENCES public.empleado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prestamo
    ADD CONSTRAINT fk_vehiculo FOREIGN KEY (id_vehiculo)
    REFERENCES public.vehiculo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;